### ISSUE TITLE
Reprocess images

### ISSUE THREAD

**Issue by flicksolutions** [DHBern/vikus-viewer#2]
Loads of images are missing in the current implementation.
Maybe I should try to generate just the spritesheets and the images with https://github.com/cpietsch/vikus-IIIF-generator. I think this part of the script worked with our current implementation of the iiif-server. What do you think @pdaengeli ? Would it be worth a try?

**Comment by pdaengeli** [comment]
I solved this by:

* exporting the csv file of the collection from the image server
* create small bash script with a bunch of curl commands
  <details><summary>script</summary>
  
  
  ```xml
  <?xml version="1.0" encoding="UTF-8"?>
  <xsl:transform xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
      xmlns:xs="http://www.w3.org/2001/XMLSchema"
      exclude-result-prefixes="xs"
      expand-text="true"
      version="3.0">
    
      <xsl:output method="text"/>
      
      <xsl:template match="/">
          <xsl:result-document href="get-iiif-files.sh" method="text" encoding="UTF-8">  
              <xsl:for-each select="unparsed-text-lines('collection-ea772d8f-1daf-4b2c-b973-314ef4c4a725-images.csv')[position() gt 2]">
                  <xsl:variable name="filename" select="(. => tokenize(';'))[7]"/>
                  <xsl:value-of>curl -L https://iiif.ub.unibe.ch/image/v3/dsl_dev/{$filename}/full/max/0/default.jpg --output {$filename => replace('\.tif','.jpg')} &#xA;</xsl:value-of>
              </xsl:for-each>            
          </xsl:result-document>
      </xsl:template>
     
  </xsl:transform>
  ```
  
  </details>

* make `./get-iiif-files.sh` executable and run it to get all jpgs from IIIF server (some patience required)
* run vikus-viewer-scripts (some more patience required)
